apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-recreate
  namespace: test
spec:
  replicas: 4
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - {key: tier, operator: In, values: [web]}
  template: 
    metadata:
      name: mytest
      namespace: dev
      labels:
        app: web
        tier: web
        env: dev
    spec:  
      containers:
      - name: testcontainer
        image: nginx:1.20.1
        ports: 
        - containerPort: 80
        resources: 
          requests:
            memory: 100Mi
            cpu: 50m
          limits: 
            memory: 500Mi
            cpu: 200m
