apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-own-pub-registry
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - {key: tier, operator: In, values: [web]}
  template: 
    metadata:
      name: mytest
      namespace: dev
      labels:
        app: web
        tier: web
        env: dev
    spec:  
      containers:
      - name: testcontainer
        image: malleshdevops/devops17-project:react-v1
        ports: 
        - containerPort: 80
