apiVersion: v1
kind: Service
metadata:
  name: liveness-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    tier: web
  ports:
    - protocol: TCP
      port: 85  
      targetPort: 80
      nodePort: 30052
