apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-liveness
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - {key: tier, operator: In, values: [web]}
  template: 
    metadata:
      name: mytest
      namespace: dev
      labels:
        app: web
        tier: web
        env: dev
    spec:  
      containers:
      - name: nginx
        image: nginx:1.20.1
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 1Gi 
        livenessProbe:
          httpGet:
            path: /
            port: 80
