apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  namespace: dev
spec:
  type: NodePort
  selector:
    tier: web
  ports:
    - protocol: TCP
      port: 85  
      targetPort: 80
