apiVersion: apps/v1
kind: Deployment
metadata:
  name: pullsecret-1
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - {key: tier, operator: In, values: [web]}
  template: 
    metadata:
      name: mytest
      namespace: dev
      labels:
        app: web
        tier: web
        env: dev
    spec:  
      containers:
      - name: testcontainer
        image: iamvkishore/k8-repo:nginx-v1
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: devops-pvt-secret
