apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    tier: web
  ports:
    - protocol: TCP
      port: 85  
      targetPort: 8080
      nodePort: 30007
